### ISSUE TITLE
if you want, add this to 2017-09-11_theory.md question Point 1

### ISSUE THREAD

**Issue by isabeauoliveri** [MartinoMensio/SDP-exams#1]
https://www.geeksforgeeks.org/mutex-vs-semaphore/

"There is an ambiguity between binary semaphore and mutex. We might have come across that a mutex is binary semaphore. But they are not! The purpose of mutex and semaphore are different. May be, due to similarity in their implementation a mutex would be referred as binary semaphore.

Strictly speaking, a mutex is locking mechanism used to synchronize access to a resource. Only one task (can be a thread or process based on OS abstraction) can acquire the mutex. It means there is ownership associated with mutex, and only the owner can release the lock (mutex).

Semaphore is signaling mechanism (“I am done, you can carry on” kind of signal). For example, if you are listening songs (assume it as one task) on your mobile and at the same time your friend calls you, an interrupt is triggered upon which an interrupt service routine (ISR) signals the call processing task to wakeup."

**Comment by MartinoMensio** [comment]
Thank you very much Isabeau! 😃 I'm adding this.

Martino
